# Generated by Django 3.2.5 on 2021-07-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
    ]
