# Generated by Django 3.2.5 on 2021-07-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['id']},
        ),
    ]
